name: Ubuntu Workflow

on: [push]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello, World!"

  list-files:
    runs-on: ubuntu-latest
    steps:
    - name: List all files
      run: ls

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  clone-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: |
        git clone https://github.com/your-username/your-repo.git
        # Add other necessary steps here if needed
